### ISSUE TITLE
Domain https://www.spotify-quiz.adarkhero.de is not running the latest version. 

### ISSUE THREAD

**Issue by DatAllmighty** [ADarkHero/Spotify-Quiz#1]
Hey. 

We noticed that the Spotify API seems to sometimes return only top hits by certain artists if querying the API search in format: artist + song name. We noticed that the latest version of code instead searches based on track ids(element.track.id), but this has not yet been deployed to https://www.spotify-quiz.adarkhero.de(see attached image of local source). I assume it fixes the problem, could it be deployed?
![image](https://github.com/ADarkHero/Spotify-Quiz/assets/47184474/e585c9cc-362d-418f-a99b-a87636e1a5fa)

**Comment by ADarkHero** [comment]
Hi!
I deployed the current version to https://www.spotify-quiz.adarkhero.de

**Comment by DatAllmighty** [comment]
Thank you!
